### ISSUE TITLE
Can't generate a new python app, getting:  NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by rezoled** [eulerrapp/nx-python#43]
* **I'm submitting a ...**
  - [X ] bug report
  - [ ] feature request
  - [ ] support request 

* **What is the current behavior?**
After creating a new NX workspace, trying to generate a python app I'm getting this error:
NOT SUPPORTED: keyword "id", use "$id" for schema ID

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
1) generate a new nx workspace (version 13.3.4)
2) npm i-D @nx-python/nx-python
3) nx g @nx-python/nx-python:app python-test
4) get an error

* **What is the expected behavior?**
To create a working python app within NX

* **What is the motivation / use case for changing the behavior?**
Support other organizational schemes for python projects.

* **Please tell us about your environment:**
  
  - Version: 1.0.3
  - OS: Window 10
  - Shell: GitBash

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
`$ nx g @nx-python/nx-python:app python-service
√ Which python framework would you like to use for the application? · flask
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID                                                     
    at Object.code (C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\vocabularies\core\id.js:6:15)    
    at keywordCode (C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\peled_rezonate\app\rezonate\node_modules\ajv\dist\compile\codegen\index.js:568:18)
NOT SUPPORTED: keyword "id", use "$id" for schema ID
`

**Comment by kylebjordahl** [comment]
Also seeing this in a new VS Code devcontainer environment, created today:

- Container OS: Debian Bullseye (image mcr.microsoft.com/vscode/devcontainers/python:0-3.8-bullseye
- Host OS: macOS 11.4 (20F71)
- Python 3.8
- Node 16.13.1

Stacktrace seems more or less the same
```
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:568:18)
```

**Comment by kylebjordahl** [comment]
Rolled back to NX 12, slightly different error:

```
"NxPython" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
TypeError: Cannot set properties of undefined (setting 'web-server')
    at /workspace/node_modules/@nrwl/workspace/src/utils/ast-utils.js:369:36
    at /workspace/node_modules/@nrwl/workspace/src/utils/ast-utils.js:359:58
    at MergeMapSubscriber.project (/workspace/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/workspace/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/workspace/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/workspace/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/workspace/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/workspace/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/workspace/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/workspace/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
```

```
  Node : 16.13.1
  OS   : linux arm64
  npm  : 8.1.2
  
  nx : 12.10.1
  @nrwl/angular : Not Found
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.10.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : 12.10.1
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.4.4
```

**Comment by wesleyyoung** [comment]
Experiencing the same issue

nx g @nx-python/nx-python:app api
✔ Which python framework would you like to use for the application? · default
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/workspace/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:568:18)

**Comment by kylebjordahl** [comment]
@wesleyyoung - check out PR #44 - you can make this change locally in your `node_modules` as a workaround for now, until it gets merged
